vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        pin_image:
            uri_prefix: /uploads/pins
            upload_destination: '%kernel.project_dir%/public/uploads/pins'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
